### ISSUE TITLE
It looks like TensorFlow Addons is building CPU operations only

### ISSUE THREAD

**Issue by plesqui** [open-ce/tensorflow-addons-feedstock#7]
Hello Open-CE community,

It appears that TensorFlow Addons is building only the operations for CPU. From the [build documentation ](https://github.com/tensorflow/addons), there seems to be an environment variable `TF_NEED_CUDA` that needs to be set. 

There are additional flags (see below) that also need to be set about CUDA but I am guessing these might be set at high level within open-ce once the build command is triggered with CUDA.

```
export TF_NEED_CUDA="1"

# Set these if the below defaults are different on your system
export TF_CUDA_VERSION="11"
export TF_CUDNN_VERSION="8"
export CUDA_TOOLKIT_PATH="/usr/local/cuda"
export CUDNN_INSTALL_PATH="/usr/lib/x86_64-linux-gnu"
```

Would it be possible to update this recipe to build on GPU as well? Thank you very much!

Kind regards,

Pedro

**Comment by jayfurmanek** [comment]
Thanks @plesqui , we’ll take a look.
I see a 12.1 version out as well so we should move to that and incorporate the gpu ops.

**Comment by jayfurmanek** [comment]
To install the cuda variant once built:

```
conda install tensorflow-addons "tensorflow-addons-proc * cuda"
```

**Comment by plesqui** [comment]
Thanks for the enhancement!
